"""
Remove null constraints.

Revision ID: 14ba4fcef118
Revises: 84b2b820a471
Create Date: 2024-08-08 14:17:20.778969
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "14ba4fcef118"
down_revision = "84b2b820a471"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "crops",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(precision=6),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_farm",
        "role",
        existing_type=postgresql.ENUM("OWNER", "MANAGER", "WORKER", "CONSULTANT", name="userrole"),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_farm",
        "role",
        existing_type=postgresql.ENUM("OWNER", "MANAGER", "WORKER", "CONSULTANT", name="userrole"),
        nullable=False,
    )
    op.alter_column(
        "crops",
        "created_at",
        existing_type=postgresql.TIMESTAMP(precision=6),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
