"""
Update relationship field  on farm  table to point to diagnosis.

Revision ID: 36aa44baa08d
Revises: aa3b19094044
Create Date: 2024-07-31 09:59:33.209933
"""
# revision identifiers, used by Alembic.
revision = "36aa44baa08d"
down_revision = "aa3b19094044"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
