"""
Update relationship field  on diagnosis  table.

Revision ID: aa3b19094044
Revises: b080eb1fe8d7
Create Date: 2024-07-31 09:54:34.217135
"""


# revision identifiers, used by Alembic.
revision = "aa3b19094044"
down_revision = "b080eb1fe8d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
