"""
Added new  table.

Revision ID: b080eb1fe8d7
Revises: 06ddb43b78eb
Create Date: 2024-07-31 09:14:30.829703
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b080eb1fe8d7"
down_revision = "06ddb43b78eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crop_diagnosis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=True),
        sa.Column("is_infected", sa.BOOLEAN(), nullable=True),
        sa.Column("crop_name", sa.String(), nullable=True),
        sa.Column("crop_type", sa.String(), nullable=True),
        sa.Column("disease_name", sa.String(), nullable=True),
        sa.Column("treatment_recommendation", sa.Text(), nullable=True),
        sa.Column("how_to_identify_disease", sa.Text(), nullable=True),
        sa.Column("causes_of_disease", sa.Text(), nullable=True),
        sa.Column("other_things_to_note", sa.Text(), nullable=True),
        sa.Column("confidence_level", sa.Float(), nullable=True),
        sa.Column("images", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(precision=6),
                  \
                   server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crop_diagnosis_id"), "crop_diagnosis", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_crop_diagnosis_id"), table_name="crop_diagnosis")
    op.drop_table("crop_diagnosis")
    # ### end Alembic commands ###
